services:
    cooperative:
        entrypoint: /config/zandronum.sh cooperative.cfg AV.WAD 10666
        env_file: passwords.env
        image: eisnerd/docker-zandronum-server
        network_mode: host
        ports:
            - '10666:10666/udp'
        restart: always
        volumes:
            - ./config:/config
            - $PWAD_DIRECTORY:/data
            - $IWAD_DIRECTORY:/iwads
    deathmatch:
        entrypoint: /config/zandronum.sh deathmatch.cfg duelpack.wad 10667
        env_file: passwords.env
        image: eisnerd/docker-zandronum-server
        network_mode: host
        ports:
            - '10667:10667/udp'
        restart: always
        volumes:
            - ./config:/config
            - $PWAD_DIRECTORY:/data
            - $IWAD_DIRECTORY:/iwads
    duel:
        entrypoint: /config/zandronum.sh duel.cfg duelpack.wad 10668
        env_file: passwords.env
        image: eisnerd/docker-zandronum-server
        network_mode: host
        ports:
            - '10668:10668/udp'
        restart: always
        volumes:
            - ./config:/config
            - $PWAD_DIRECTORY:/data
            - $IWAD_DIRECTORY:/iwads
    web:
        image: sebp/lighttpd
        network_mode: host
        ports:
            - '80:80'
        restart: always
        volumes:
            - ./lighttpd:/etc/lighttpd
            - $PWAD_DIRECTORY:/var/www/localhost/htdocs
version: '3'
