services:
    cooperative:
        entrypoint: /config/zandronum.sh cooperative.cfg AV.WAD
        env_file: passwords.env
        image: eisnerd/docker-zandronum-server
        ports:
            - '10666:10666/udp'
        restart: always
        volumes:
            - ./config:/config
            - $PWAD_DIRECTORY:/data
            - $IWAD_DIRECTORY:/iwads
    deathmatch:
        entrypoint: /config/zandronum.sh deathmatch.cfg duelpack.wad
        env_file: passwords.env
        image: eisnerd/docker-zandronum-server
        ports:
            - '10667:10666/udp'
        restart: always
        volumes:
            - ./config:/config
            - $PWAD_DIRECTORY:/data
            - $IWAD_DIRECTORY:/iwads
    duel:
        entrypoint: /config/zandronum.sh duel.cfg duelpack.wad
        env_file: passwords.env
        image: eisnerd/docker-zandronum-server
        ports:
            - '10668:10666/udp'
        restart: always
        volumes:
            - ./config:/config
            - $PWAD_DIRECTORY:/data
            - $IWAD_DIRECTORY:/iwads
    web:
        image: sebp/lighttpd
        ports:
            - '80:80'
        restart: always
        volumes:
            - ./lighttpd:/etc/lighttpd
            - $PWAD_DIRECTORY:/var/www/localhost/htdocs
version: '3'
